---
name: Pre Commit Checks
description: Runs ansible-lint action to check for code quality and style issues
author: 'Nanda Bala'
inputs:
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.13.0'
  ansible_lint_config:
    description: 'relative path to ansible lint config file'
    required: false
  ansible_requirements_file:
    description: 'ansible requirements file for role and collection dependencies'
    required: false
  ansible_extra_args:
    description: 'List of extra arguments to pass to ansible-lint'
    required: false
    default: ''
  ansible_directory:
    description: 'relative path to ansible directory'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Prepare configurations
      shell: bash
      run: |-
        mkdir -p /tmp
        cp -f ${{ inputs.ansible_requirements_file != '' && inputs.ansible_requirements_file || format('{0}/requirements.yaml', github.action_path) }} /tmp/requirements.yaml
        cp -f ${{ inputs.ansible_lint_config != '' && inputs.ansible_lint_config || format('{0}/.ansible-lint.yaml', github.action_path) }} /tmp/.ansible-lint.yaml
    - name: Run ansible-lint
      uses: ansible/ansible-lint@e918e02374cc9148abfe6d0fa04417ee89f0def9  # v25
      with:
        setup_python: "true"
        args: "--config-file /tmp/.ansible-lint.yaml --force-color ${{ inputs.ansible_lint_args}}"
        working_directory: "${{ github.workspace }}/${{ inputs.ansible_directory }}"
        requirements_file: "/tmp/requirements.yaml"

branding:
  icon: 'check'
  color: 'blue'